spring:
  application:
    name: module-common
  config:
    import: 'aws-parameterstore:/config/tripot_prod/'

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: tripot