spring:
  application:
    name: module-api
  jwt:
    secret: ${JWT_SECRET_KEY}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB



  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_SECRET_KEY}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    root: info


cloud:
  aws:
    s3:
      bucket: tripot
      path:
        profile: user/profile
        story: story/image
      region:
        static: eu-north-1
      stack:
        auto: false
      credentials:
        accessKey: ${AWS_S3_ACCESS_KEY_ID}
        secretKey: ${AWS_S3_SECRET_ACCESS_KEY}

