spring:
  application:
    name: module-api
  profiles:
    group:
      "local": "local"
      "prod": "prod"

management:
  endpoints:
    web:
      exposure:
        include: health

#  config:
#    import: aws-parameterstore:/config/tripot-prod/
#
#aws:
#  paramstore:
#    enabled: true
#    prefix: /config
#    name: tripot
#    profile-separator: '-'
