spring:
  application:
    name: module-api
  jwt:
    secret: ${JWT_SECRET_KEY}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB


logging:
  level:
    root: info

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_SECRET_KEY}


cloud:
  aws:
    s3:
      bucket: tripot
      path:
        profile: user/profile/
        story: story/image
      region:
        static: eu-north-1
      stack:
        auto: false
      credentials:
        accessKey: ${AWS_S3_ACCESS_KEY_ID}
        secretKey: ${AWS_S3_SECRET_ACCESS_KEY}



