spring:
  application:
    name: module-api
  jwt:
    secret: ${JWT_SECRET_KEY}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

oauth2:
  apple:
    client-id: ${APPLE_CLIENT_ID}
    pk-host: ${APPLE_PK_HOST}


cloud:
  aws:
    s3:
      bucket: tripot-asia
      path:
        profile: user/profile/
        story: story/image
        question: question/
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        accessKey: ${AWS_S3_ACCESS_KEY_ID}
        secretKey: ${AWS_S3_SECRET_ACCESS_KEY}

data-api:
  festival:
    url: ${FESTIVAL_URL}
    key: ${FESTIVAL_API_KEY}
  festival-detail:
    url: ${FESTIVAL_DETAIL_URL}
    key: ${FESTIVAL_API_KEY}

admin-web:
  url:
    dev: ${ADMIN_WEB_DEV}
    prod: ${ADMIN_WEB_PROD}
