spring:
  datasource:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# jpa.show-sql과 같은 동작을 하나 logger의 특성 적용
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace