spring:
  config:
    activate:
      on-profile: dev
  application:
    name: module-domain
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}