spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/tripot
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  data:
    redis:
      host: localhost
      port: 6379
  logging:
    level:
      org.hibernate.SQL: info
      org.hibernate.type: trace
  data:
    redis:
      host: localhost
      port: 6379

