name: CICD Tripot Prod
run-name: Running
on:
  push:
    branches:
      - main

jobs:
  build-with-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 프로젝트 빌드(테스트 코드 제외)
        run: |
          ./gradlew clean build --exclude-task test

      # docker login -u username -p password
      - name: docker 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tripot-prod . -f prod.Dockerfile


      - name: docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tripot-prod:latest


      - name: Deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 퍼블릭 IPv4 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22

          script: |
            sudo touch prod.env
              echo "${{ secrets.ENV_VARS_PROD }}" | sudo tee prod.env > /dev/null
            
            
            sudo touch docker-compose-prod.yml
              echo "${{ vars.DOCKER_COMPOSE_PROD }}" | sudo tee docker-compose-prod.yml > /dev/null
            
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            chmod +x /home/ubuntu/prod-deploy.sh
            /home/ubuntu/prod-deploy.sh
