name: CICD Tripot Dev
run-name: Running
on:
  push:
    branches:
      - develop

jobs:
  build-with-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 프로젝트 빌드(테스트 코드 제외)
        run: |
          ./gradlew clean build --exclude-task test

      # docker login -u username -p password
      - name: docker 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tripot-dev . -f dev.Dockerfile


      - name: docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tripot-dev:latest

      - name: Deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 퍼블릭 IPv4 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22

          script: |
            
            
            sudo touch dev.env
              echo "${{ secrets.ENV_VARS_DEV }}" | sudo tee dev.env > /dev/null
            
            
            sudo touch docker-compose-dev.yml
              echo "${{ vars.DOCKER_COMPOSE_DEV }}" | sudo tee docker-compose.yml > /dev/null
            
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/tripot-dev:latest
            docker compose -f docker-compose-dev.yml --env-file ./dev.env up -d
            sudo docker image prune -f